In [1]:
#エクセルシートを読み込む

import openpyxl

#エクセルファイルを開く
wb = openpyxl.load_workbook('【ローデータ・GT表】2403運転免許保有者に関する調査.xlsx')

In [2]:
#特定のシートを開く

sheet = wb['基準クリア年齢性別順']

In [3]:
import pandas as pd

df_in = pd.read_excel('【ローデータ・GT表】2403運転免許保有者に関する調査.xlsx', sheet_name='基準クリア年齢性別順')
df_in

,no,group1,group2,sc1,sc2_1,sc3,sc4,sc5-1,sc5-2,sc5-3,...,aq-1,aq-2,bq-1,bq-2,cq-1,cq-2,dq-1,dq-2,eq-1,eq-2
0,87,1,1,1,28,14,1,0,0,1,...,1,0,1,0,1,0,1,0,1,0
1,105,1,1,1,28,1,2,1,0,0,...,1,0,1,0,1,0,1,0,1,0
2,109,1,1,1,28,11,2,1,0,0,...,1,0,1,0,1,0,1,0,1,0
3,119,1,1,1,20,21,1,0,0,1,...,1,0,1,0,1,0,1,0,1,0
4,145,1,1,1,27,13,2,0,0,1,...,1,0,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,2984,12,23,2,72,40,2,1,0,0,...,1,0,1,0,1,0,1,0,1,0
800,2989,12,23,2,71,13,2,0,1,0,...,1,0,1,0,1,0,1,0,1,0
801,2992,12,23,2,72,13,2,0,0,1,...,1,0,1,0,1,0,1,0,1,0
802,2994,12,23,2,75,43,2,0,1,0,...,1,0,1,0,1,0,1,0,1,0
803,2996,12,23,2,75,28,2,0,1,0,...,1,0,1,0,1,0,1,0,1,0

In [8]:
#欠損値の確認
df_in.isnull().sum()

#欠損値のある変数のみを抽出
df_in.isnull().sum()[df_in.isnull().sum()>0]

q1_snt4_1    804
q2_snt4_1    804
q6            88
q7            88
q8           804
q9            88
q10           88
dtype: int64

In [6]:
df_out = pd.read_excel('主観評価設問状態_origin_出力100.xlsx')
df_out

,好み1,不快1,個人的に好き1,なぜ危険なのか1,どのように改善したらよいか1,なるほど1,自分には関係ない1,改善しようと思う1,これからは注意して運転しよう1,急ブレーキのたびに出たら不快1,...,たまに出てきても問題ない5,何度も出てきたら煩わしく5,ブレーキに関する内容5,自分の運転に対する内容5,何の操作に対する指摘かよくわからなかった5,分かりやすかった5,理解しやすかった5,指摘内容の把握を流暢に5,把握は楽5,難しかった5
0,1,3,2,1,1,1,3,3,1,3,...,3,4,4,4,4,4,4,4,4,4
1,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
2,1,5,1,1,5,1,5,1,1,1,...,1,4,4,5,2,5,5,3,5,2
3,3,3,3,1,5,1,1,1,1,1,...,3,4,5,4,5,4,4,4,4,3
4,1,1,1,1,1,1,1,1,1,5,...,1,1,5,5,4,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,3,5,3,1,1,1,3,1,3,3,...,2,3,5,5,5,5,5,5,5,5
800,1,5,1,1,5,1,5,1,1,1,...,5,2,5,5,1,5,5,5,5,5
801,5,1,5,5,1,4,1,5,5,5,...,1,5,5,5,1,5,5,5,5,1
802,1,5,1,1,5,1,1,1,3,5,...,4,4,5,5,5,5,5,5,5,5
803,1,5,1,1,5,1,5,1,1,3,...,3,1,4,4,5,5,4,4,4,5